2025-02-12 22:12:53,416 INFO    MainThread:3530446 [wandb_setup.py:_flush():68] Current SDK version is 0.19.6
2025-02-12 22:12:53,417 INFO    MainThread:3530446 [wandb_setup.py:_flush():68] Configure stats pid to 3530446
2025-02-12 22:12:53,417 INFO    MainThread:3530446 [wandb_setup.py:_flush():68] Loading settings from /n/home09/michaelzhao/.config/wandb/settings
2025-02-12 22:12:53,417 INFO    MainThread:3530446 [wandb_setup.py:_flush():68] Loading settings from /n/home09/michaelzhao/Downloads/thesis/topic_taxonomy_expansion/wandb/settings
2025-02-12 22:12:53,417 INFO    MainThread:3530446 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-02-12 22:12:53,417 INFO    MainThread:3530446 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /n/home09/michaelzhao/Downloads/thesis/topic_taxonomy_expansion/wandb/run-20250212_221253-7gxwravd/logs/debug.log
2025-02-12 22:12:53,417 INFO    MainThread:3530446 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /n/home09/michaelzhao/Downloads/thesis/topic_taxonomy_expansion/wandb/run-20250212_221253-7gxwravd/logs/debug-internal.log
2025-02-12 22:12:53,417 INFO    MainThread:3530446 [wandb_init.py:init():756] calling init triggers
2025-02-12 22:12:53,417 INFO    MainThread:3530446 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-02-12 22:12:53,418 INFO    MainThread:3530446 [wandb_init.py:init():789] starting backend
2025-02-12 22:12:53,711 INFO    MainThread:3530446 [wandb_init.py:init():793] sending inform_init request
2025-02-12 22:12:53,738 INFO    MainThread:3530446 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-02-12 22:12:53,739 INFO    MainThread:3530446 [wandb_init.py:init():808] backend started and connected
2025-02-12 22:12:53,761 ERROR   MainThread:3530446 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/n/home09/michaelzhao/Downloads/topicexpan/myenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/home09/michaelzhao/Downloads/topicexpan/myenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 811, in init
    run = Run(
          ^^^^
  File "/n/home09/michaelzhao/Downloads/topicexpan/myenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 573, in __init__
    self._init(
  File "/n/home09/michaelzhao/Downloads/topicexpan/myenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 589, in _init
    self._config = wandb_config.Config()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/n/home09/michaelzhao/Downloads/topicexpan/myenv/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 105, in __init__
    self._load_defaults()
  File "/n/home09/michaelzhao/Downloads/topicexpan/myenv/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 252, in _load_defaults
    conf_dict = config_util.dict_from_config_file("config-defaults.yaml")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/home09/michaelzhao/Downloads/topicexpan/myenv/lib/python3.12/site-packages/wandb/sdk/lib/config_util.py", line 90, in dict_from_config_file
    data[k] = v["value"]
              ~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
2025-02-12 22:12:53,896 WARNING MsgRouterThr:3530446 [router.py:message_loop():75] message_loop has been closed
